import "@/app/globals.css";

import { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { TailwindIndicator } from "@/components/theme/tailwind-indicator";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased overflow-hidden",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ScrollArea className="h-screen">{children}</ScrollArea>
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
